import { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    en: {
        home: "Home",
        explore: "Explore",
        offers: "Offers",
        about: "About Us",
        login: "Login",
        searchPlaceholder: "Search for restaurants, cuisines...",
        searchBtn: "Search",
        heroTitle: "Discover & Book World Class Dining",
        heroSubtitle: "The easiest way to find your next favorite restaurant in Jordan. Seamless reservations, exclusive offers, and unforgettable experiences.",
        featuredTitle: "Featured Restaurants",
        featuredSubtitle: "Handpicked selections in Amman and beyond.",
        viewAll: "View All",
        exclusiveOffers: "Exclusive Offers",
        limitedTime: "Limited Time",
        exploreDining: "Explore Dining",
        viewDetails: "View Details",
        bookTable: "Book a Table",
        openingHours: "Opening Hours",
        contact: "Contact",
        aboutExperience: "About the Experience",
        popularDishes: "Popular Dishes",
        viewMenu: "View Full Menu",
        makeReservation: "Make a Reservation",
        completeReservation: "Complete Reservation",
        selectDate: "Select Date",
        time: "Time",
        guests: "Guests",
        continue: "Continue",
        back: "Back",
        confirmBooking: "Confirm Booking",
        fullName: "Full Name",
        email: "Email Address",
        phone: "Phone Number",
        bookingConfirmed: "Booking Confirmed!",
        bookingSent: "We've sent a confirmation email to",
        done: "Done",
        footerDesc: "Making dining experiences memorable. Book the best tables, discover new flavors, and enjoy seamless service in Jordan.",
        quickLinks: "Quick Links",
        support: "Support",
        newsletter: "Newsletter",
        subscribe: "Subscribe for latest offers and updates.",
        join: "Join",
        rights: "TableEase. All rights reserved.",
        cuisines: {
            All: "All",
            Jordanian: "Jordanian",
            Italian: "Italian",
            Cafe: "Cafe",
            Levantine: "Levantine",
            International: "International"
        },
        loginTitle: "Welcome Back",
        loginSubtitle: "Sign in to manage your bookings",
        password: "Password",
        signIn: "Sign In",
        noAccount: "Don't have an account?",
        register: "Register here",
        aboutTitle: "About TableEase",
        aboutContent: "TableEase is Jordan's premier restaurant reservation platform. We bridge the gap between discerning diners and the country's finest culinary establishments.",
        ourMission: "Our Mission",
        missionContent: "To simplify the dining experience while celebrating the rich hospitality culture of Jordan.",
        newsletterSuccess: "Thanks for subscribing!",
        menuTitle: "Full Menu",
        close: "Close",
        // Dashboard
        dashboard: "Dashboard",
        overview: "Overview",
        myRestaurant: "My Restaurant",
        bookings: "Bookings",
        settings: "Settings",
        logout: "Logout",
        stats: {
            totalBookings: "Total Bookings",
            revenue: "Revenue",
            views: "Page Views",
            rating: "Rating"
        },
        manageRestaurant: "Manage Restaurant",
        restaurantName: "Restaurant Name",
        cuisineType: "Cuisine Type",
        saveChanges: "Save Changes",
        recentBookings: "Recent Bookings",
        status: "Status",
        actions: "Actions",
        accept: "Accept",
        reject: "Reject",
        pending: "Pending",
        confirmed: "Confirmed",
        loginAsPartner: "Login as Partner",
        loginAsDiner: "Login as Diner",
        // Register
        createAccount: "Create Account",
        joinMessage: "Join TableEase today",
        confirmPassword: "Confirm Password",
        alreadyHaveAccount: "Already have an account?",
        // Payment
        payment: "Payment",
        paymentDesc: "Secure your reservation with a deposit.",
        payWith: "Pay with",
        creditCard: "Credit / Debit Card",
        cliq: "CliQ (Instant Pay)",
        cardNumber: "Card Number",
        expiryDate: "Expiry Date",
        cvv: "CVV",
        cardHolder: "Cardholder Name",
        cliqAlias: "CliQ Alias / Mobile",
        payNow: "Pay Now",
        reservationDeposit: "Reservation Deposit",
        amount: "Amount",
        loginToBook: "Please login to make a reservation.",
        // Validation
        invalidEmailFormat: "Invalid email format",
        passwordsDoNotMatch: "Passwords do not match!",
        passwordStrength: "Password must be strong (8+ chars, 1 uppercase, 1 number, 1 special char).",
        isRequired: "is required",

        // Dashboard Generic
        homePage: "Home Page",
        profile: "Profile",
        success: "Success",
        changesSaved: "Changes saved successfully!",

        // My Restaurant
        generalInfo: "General Information",
        description: "Description",
        seatingCapacity: "Seating & Capacity",
        mainHall: "Main Hall",
        terrace: "Terrace",
        photos: "Photos",
        location: "Location",
        addressCity: "Address / City",
        priceRange: "Price Range",
        amenities: "Amenities",
        dishName: "Dish Name",
        dishDesc: "Dish Description",
        price: "Price",
        addDish: "Add Dish",
        nameEn: "Restaurant Name (EN)",
        nameAr: "Restaurant Name (AR)",
        descEn: "Description (EN)",
        descAr: "Description (AR)",
        // Payments
        checkout: "Checkout",
        payByCard: "Credit/Debit Card",
        payByCliq: "CliQ Transfer",
        payByWallet: "E-Wallet",
        payAtRestaurant: "Pay at Restaurant",
        clicAliasLabel: "Your CliQ Alias / Mobile",
        walletNumLabel: "Wallet Mobile Number",
        confirmPay: "Confirm Payment",
        processing: "Processing...",
        paymentNote: "Secure payment powered by TableEase",
        processing: "Processing...",
        paymentNote: "Secure payment powered by TableEase",
        bookingRequestReceived: "Booking Request Received ⏳",
        bookingPendingMsg: "We have received your request. We will review it and send a WhatsApp confirmation shortly.",
        bookingSentWhatsApp: "Your booking is confirmed! Send the details via WhatsApp to finalize.", // Keep for legacy or unexpected flows

        // Admin WhatsApp Messages
        whatsappConfirmMsg: "Hello, your booking at *{restaurant}* has been confirmed! ✅\nWe look forward to hosting you.",
        whatsappRejectMsg: "Hello, regarding your booking at *{restaurant}*.\nUnfortunately, we cannot confirm your reservation due to full capacity. ❌\nWe apologize for the inconvenience.",
        priceLevels: {
            budget: "Budget ($)",
            casual: "Casual ($$)",
            upscale: "Upscale ($$$)",
            luxury: "Luxury ($$$$)"
        },

        // Settings
        account: "Account",
        personalInfo: "Personal Information",
        edit: "Edit",
        preferences: "Preferences",
        change: "Change",
        theme: "Theme",
        darkMode: "Dark Mode",
        lightMode: "Light Mode",
        notifications: "Notifications",
        emailSMS: "Email & SMS",
        configure: "Configure",
        security: "Password & Security",
        lastChanged: "Last changed recently",
        update: "Update",
        editProfile: "Edit Profile",
        notificationPreferences: "Notification Preferences",
        emailNotifications: "Email Notifications",
        smsAlerts: "SMS Alerts",
        promotionalOffers: "Promotional Offers",
        updatePassword: "Update Password",
        currentPassword: "Current Password",
        newPassword: "New Password",
        cancel: "Cancel"
    },
    ar: {
        home: "الرئيسية",
        explore: "استكشف",
        offers: "العروض",
        about: "من نحن",
        login: "تسجيل دخول",
        searchPlaceholder: "ابحث عن مطاعم، مأكولات...",
        searchBtn: "بحث",
        heroTitle: "اكتشف واحجز أفضل تجارب الطعام",
        heroSubtitle: "أسهل طريقة للعثور على مطعمك المفضل التالي في الأردن. حجوزات سلسة، عروض حصرية، وتجارب لا تُنسى.",
        featuredTitle: "مطاعم مميزة",
        featuredSubtitle: "خيارات مختارة لك في عمان وغيرها.",
        viewAll: "عرض الكل",
        exclusiveOffers: "عروض حصرية",
        limitedTime: "لفترة محدودة",
        exploreDining: "استكشف المطاعم",
        viewDetails: "التفاصيل",
        bookTable: "احجز طاولة",
        openingHours: "ساعات العمل",
        contact: "تواصل معنا",
        aboutExperience: "عن التجربة",
        popularDishes: "أطباق شائعة",
        viewMenu: "عرض القائمة الكاملة",
        makeReservation: "قم بالحجز",
        completeReservation: "إكمال الحجز",
        selectDate: "اختر التاريخ",
        time: "الوقت",
        guests: "الضيوف",
        continue: "متابعة",
        back: "رجوع",
        confirmBooking: "تأكيد الحجز",
        fullName: "الاسم الكامل",
        email: "البريد الإلكتروني",
        phone: "رقم الهاتف",
        bookingConfirmed: "تم الحجز بنجاح!",
        bookingSent: "لقد أرسلنا رسالة تأكيد إلى",
        done: "تم",
        footerDesc: "نجعل تجارب الطعام لا تُنسى. احجز أفضل الطاولات، واكتشف نكهات جديدة، واستمتع بخدمة سلسة في الأردن.",
        quickLinks: "روابط سريعة",
        support: "دعم",
        newsletter: "النشرة البريدية",
        subscribe: "اشترك للحصول على آخر العروض والتحديثات.",
        join: "انضم",
        rights: "TableEase. جميع الحقوق محفوظة.",
        cuisines: {
            All: "الكل",
            Jordanian: "أردني",
            Italian: "إيطالي",
            Cafe: "كافيه",
            Levantine: "شامي",
            International: "عالمي"
        },
        loginTitle: "أهلاً بك مجدداً",
        loginSubtitle: "سجل دخولك لإدارة حجوزاتك",
        password: "كلمة المرور",
        signIn: "دخول",
        noAccount: "ليس لديك حساب؟",
        register: "سجل هنا",
        aboutTitle: "عن TableEase",
        aboutContent: "TableEase هي منصة حجز المطاعم الأولى في الأردن. نحن نجسد الجسر بين عشاق الطعام وأرقى الوجهات في المملكة.",
        ourMission: "مهمتنا",
        missionContent: "تسهيل تجربة تناول الطعام مع الاحتفاء بثقافة الضيافة الغنية في الأردن.",
        newsletterSuccess: "شكراً لاشتراكك!",
        menuTitle: "القائمة الكاملة",
        close: "إغلاق",
        // Dashboard
        dashboard: "لوحة التحكم",
        overview: "نظرة عامة",
        myRestaurant: "مطعمي",
        bookings: "الحجوزات",
        settings: "الإعدادات",
        logout: "تسجيل خروج",
        stats: {
            totalBookings: "مجموع الحجوزات",
            revenue: "الإيرادات",
            views: "المشاهدات",
            rating: "التقييم"
        },
        manageRestaurant: "إدارة المطعم",
        restaurantName: "اسم المطعم",
        cuisineType: "نوع المطبخ",
        saveChanges: "حفظ التغييرات",
        recentBookings: "آخر الحجوزات",
        status: "الحالة",
        actions: "إجراءات",
        accept: "قبول",
        reject: "رفض",
        pending: "قيد الانتظار",
        confirmed: "مؤكد",
        loginAsPartner: "دخول كشريك (مطعم)",
        loginAsDiner: "دخول كزبون",
        // Register
        createAccount: "إنشاء حساب",
        joinMessage: "انضم إلى TableEase اليوم",
        confirmPassword: "تأكيد كلمة المرور",
        alreadyHaveAccount: "لديك حساب بالفعل؟",
        // Payment
        payment: "الدفع",
        paymentDesc: "قم بتأكيد حجزك بدفع العربون.",
        payWith: "ادفع بواسطة",
        creditCard: "بطاقة ائتمان / خصم",
        cliq: "كليك (دفع فوري)",
        cardNumber: "رقم البطاقة",
        expiryDate: "تاريخ الانتهاء",
        cvv: "CVV",
        cardHolder: "اسم حامل البطاقة",
        cliqAlias: "اسم كليك المستعار / الموبايل",
        payNow: "ادفع الآن",
        reservationDeposit: "عربون الحجز",
        amount: "المبلغ",
        loginToBook: "يرجى تسجيل الدخول للحجز.",

        // Validation
        invalidEmailFormat: "صيغة البريد الإلكتروني غير صحيحة",
        passwordsDoNotMatch: "كلمتا المرور غير متطابقتين!",
        passwordStrength: "يجب أن تكون كلمة المرور قوية (8+ أحرف، كبير، صغير، رقم، رمز).",
        isRequired: "مطلوب",

        // Dashboard Generic
        homePage: "الرئيسية للموقع",
        profile: "الملف الشخصي",
        success: "نجاح",
        changesSaved: "تم حفظ التغييرات بنجاح!",

        // My Restaurant
        generalInfo: "معلومات عامة",
        description: "الوصف",
        seatingCapacity: "المقاعد والسعة",
        mainHall: "الصالة الرئيسية",
        terrace: "التراس",
        photos: "الصور",
        location: "الموقع",
        addressCity: "العنوان / المدينة",
        priceRange: "نطاق الأسعار",
        amenities: "المرافق",
        dishName: "اسم الطبق",
        dishDesc: "وصف الطبق",
        price: "السعر",
        addDish: "إضافة طبق",
        nameEn: "اسم المطعم (EN)",
        nameAr: "اسم المطعم (AR)",
        descEn: "الوصف (EN)",
        descAr: "الوصف (AR)",
        // Payments
        checkout: "الدفع",
        payByCard: "بطاقة ائتمان",
        payByCliq: "تحويل كليك",
        payByWallet: "محفظة إلكترونية",
        payAtRestaurant: "الدفع عند الوصول",
        clicAliasLabel: "اسمك المستعار على كليك / رقم الهاتف",
        walletNumLabel: "رقم المحفظة",
        confirmPay: "تأكيد الدفع",
        processing: "جاري المعالجة...",
        paymentNote: "دفع آمن عبر TableEase",
        processing: "جاري المعالجة...",
        paymentNote: "دفع آمن عبر TableEase",
        bookingRequestReceived: "تم استلام طلب الحجز ⏳",
        bookingPendingMsg: "سيتم مراجعة طلبك وإرسال رسالة تأكيد عبر واتساب خلال وقت قصير.",
        bookingSentWhatsApp: "تم تأكيد الحجز! أرسل التفاصيل عبر الواتساب لإتمامه.",

        // Admin WhatsApp Messages
        whatsappConfirmMsg: "مرحباً، تم تأكيد حجزك في *{restaurant}* بنجاح! ✅\nشكراً لثقتك بنا، ونتمنى لك تجربة ممتعة.",
        whatsappRejectMsg: "مرحباً، بخصوص حجزك في *{restaurant}*.\nنعتذر، لم يتم تأكيد الحجز بسبب عدم توفر المقاعد. ❌\nيسعدنا خدمتك في وقت آخر.",
        priceLevels: {
            budget: "اقتصادي ($)",
            casual: "متوسط ($$)",
            upscale: "راقي ($$$)",
            luxury: "فاخر ($$$$)"
        },

        // Settings
        account: "الحساب",
        personalInfo: "المعلومات الشخصية",
        edit: "تعديل",
        preferences: "التفضيلات",
        change: "تغيير",
        theme: "المظهر",
        darkMode: "الوضع الليلي",
        lightMode: "الوضع النهاري",
        notifications: "الإشعارات",
        emailSMS: "البريد والرسائل",
        configure: "تكوين",
        security: "الأمان وكلمة المرور",
        lastChanged: "آخر تغيير مؤخراً",
        update: "تحديث",
        editProfile: "تعديل الملف الشخصي",
        notificationPreferences: "تفضيلات الإشعارات",
        emailNotifications: "إشعارات البريد",
        smsAlerts: "تنبيهات SMS",
        promotionalOffers: "عروض ترويجية",
        updatePassword: "تحديث كلمة المرور",
        currentPassword: "كلمة المرور الحالية",
        newPassword: "كلمة المرور الجديدة",
        cancel: "إلغاء"
    }
};

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState('en'); // Default to English

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'en' ? 'ar' : 'en');
    };

    useEffect(() => {
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language]);

    return (
        <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t: translations[language] }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => useContext(LanguageContext);
