import { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    en: {
        home: "Home",
        explore: "Explore",
        offers: "Offers",
        about: "About Us",
        login: "Login",
        searchPlaceholder: "Search for restaurants or cafés…",
        searchBtn: "Search",
        heroTitle: "Discover & Book Exceptional Dining & Café Experiences",
        heroSubtitle: "Find and reserve your next favorite restaurant or café in Jordan — seamless bookings, exclusive offers, and unforgettable moments.",
        featuredTitle: "Featured Establishments",
        featuredSubtitle: "Handpicked premium restaurants and cafés, curated by TableEase for exceptional dining experiences.",
        viewAll: "View All",
        exclusiveOffers: "Exclusive Offers",
        limitedTime: "Limited Time",
        exploreDining: "Explore Venues",
        discoverDesc: "Discover Jordan’s most exceptional dining and café experiences.",
        viewDetails: "View Details",
        bookTable: "Book a Table",
        claimNow: "Claim Now",
        offersSubtitle: "Exclusive deals and limited-time offers from our partners.",
        restaurantNotFound: "Venue not found.",
        noMenuHighlights: "No menu highlights added yet.",
        openingHours: "Opening Hours",
        contact: "Contact",
        aboutExperience: "About the Venue",
        popularDishes: "Popular Selection",
        viewMenu: "View Full Menu",
        fullMenu: "Full Menu",
        makeReservation: "Make a Reservation",
        completeReservation: "Complete Reservation",
        selectDate: "Select Date",
        time: "Time",
        requests: "Requests",
        bookingsManagement: "Bookings Management",
        idLabel: "ID",
        dateTime: "Date & Time",
        contactLabel: "Contact",
        noBookingsFound: "No bookings found.",
        deleteHistoryConfirm: "Are you sure you want to delete all booking history?",
        clearHistory: "Clear History",
        guests: "Guests",
        continue: "Continue",
        back: "Back",
        confirmBooking: "Confirm Booking",
        fullName: "Full Name",
        email: "Email Address",
        phone: "Phone Number",
        bookingConfirmed: "Booking Confirmed!",
        bookingSent: "We've sent a confirmation email to",
        done: "Done",
        footerDesc: "Making your visits memorable. Book the best tables, discover new flavors, and enjoy seamless service in Jordan's finest restaurants and cafes.",
        quickLinks: "Quick Links",
        support: "Support",
        newsletter: "Newsletter",
        subscribe: "Subscribe for latest offers and updates.",
        tagline: "TableEase • Jordan's Premier Booking Hub for Restaurants & Cafes",
        helpCenter: "Help Center",
        allBookings: "All Bookings",
        today: "Today",
        tomorrow: "Tomorrow",
        thisWeek: "This Week",
        tableManagement: "Table Management",
        addTable: "Add Table",
        tableName: "Table Name/Number",
        capacity: "Capacity",
        status: "Status",
        active: "Active",
        disabled: "Disabled",
        noTables: "No tables defined. Add your first table!",
        suitableTableAllocated: "A suitable table has been allocated for you.",
        noSuitableTables: "No suitable tables available at this time.",
        tableSettings: "Table Settings",
        saveTable: "Save Table",
        editTable: "Edit Table",
        deleteTable: "Delete Table",
        persons: "Persons",
        defaultDuration: "Default Duration (Minutes)",
        bufferTime: "Buffer Time (Minutes)",
        termsOfService: "Terms of Service",
        privacyPolicy: "Privacy Policy",
        lastUpdatedLabel: "Last Updated",
        january2025: "January 2025",
        privacyQuote: "Your trust is our most valuable asset. We treat your data with the same care we would our own.",
        privacyTeam: "— TableEase Team",
        stillQuestions: "Still have questions?",
        stillQuestionsDesc: "If you need clarification about any of our terms, please don't hesitate to reach out to our support team.",
        contactSupport: "Contact Support",
        faqTitle: "Frequently Asked Questions",
        faqs: [
            {
                q: "How do I book a table?",
                a: "Select the restaurant, choose the date, time, and number of people, then enter your details and click 'Confirm Booking'."
            },
            {
                q: "Do I need to create an account?",
                a: "No. You can book directly via Quick Reserve using only your name and phone number."
            },
            {
                q: "What does it mean if the booking is 'Pending'?",
                a: "It means your request has been sent to the restaurant and is awaiting confirmation or rejection from the management."
            },
            {
                q: "Can I cancel my booking?",
                a: "It depends on the restaurant's policy. If a Deposit was paid, special terms may apply."
            },
            {
                q: "How do I add a restaurant to my favorites?",
                a: "Click on the ❤️ icon inside the restaurant page, and it will be saved to your favorites list."
            },
            {
                q: "I am a restaurant owner, how do I join?",
                a: "You can register via the 'Join as a Restaurant' page, and we will contact you to set up your account."
            }
        ],
        welcomeBackAdmin: "Welcome back, Admin",
        noResults: "No results found.",
        exclusiveOffer: "Exclusive Offer",
        vibeFinderTitle: "Find Your Perfect Match",
        vibeFinderSubtitle: "Answer 4 quick questions and we'll find the ideal dining spot for you.",
        startVibeFinder: "Start Vibe Finder",
        termsContent: [
            {
                title: "1. Introduction",
                desc: "By using the TableEase platform, you agree to comply with the terms of service outlined below."
            },
            {
                title: "2. Nature of Service",
                desc: "TableEase is an intermediary platform connecting users and restaurants, and does not take responsibility for the quality of service provided within the restaurant."
            },
            {
                title: "3. Bookings",
                desc: "Booking is subject to restaurant approval. Bookings may be rejected or modified based on table availability. Some bookings may require a security deposit."
            },
            {
                title: "4. Cancellation and No-Show",
                desc: "Cancellation policies vary from one restaurant to another. In case of a no-show, the deposit may be deducted according to the restaurant's policy."
            },
            {
                title: "5. Acceptable Use",
                desc: "It is forbidden to: misuse the platform, provide incorrect information, or attempt to disrupt or exploit the system."
            },
            {
                title: "6. Amendments",
                desc: "TableEase reserves the right to modify these terms at any time, and users will be notified when material changes occur."
            }
        ],
        privacyContent: [
            {
                title: "1. Information Collection",
                desc: "We collect the following information: Name, Phone Number, Booking Details, User Preferences (such as favorite restaurants)."
            },
            {
                title: "2. Use of Information",
                desc: "We use your data to: Complete bookings, improve user experience, and communicate regarding the booking."
            },
            {
                title: "3. Data Sharing",
                desc: "We do not sell or share your data with third parties, except for: The restaurant where the booking was made, and payment services when needed."
            },
            {
                title: "4. Data Protection",
                desc: "We are committed to taking technical and organizational measures to protect user data from unauthorized access."
            },
            {
                title: "5. Cookies",
                desc: "We may use cookies to improve performance and user experience."
            },
            {
                title: "6. User Rights",
                desc: "You have the right to: Request data modification, request data deletion, and inquire about how your information is used."
            }
        ],
        guarantee: "Guarantee",
        available: "Available",
        arabic: "Arabic",
        english: "English",
        join: "Join",
        rights: "TableEase. All rights reserved.",
        cuisines: {
            All: "All",
            Jordanian: "Jordanian",
            Italian: "Italian",
            Cafe: "Cafe",
            Levantine: "Levantine",
            International: "International"
        },
        loginTitle: "Welcome Back",
        loginSubtitle: "Sign in to manage your restaurant or café on TableEase",
        password: "Password",
        signIn: "Sign In",
        noAccount: "Own a restaurant or café?",
        register: "Join TableEase",
        aboutTitle: "TableEase",
        aboutTagline: "Book your table in seconds. Leave the chaos behind.",
        aboutDescription: "TableEase is a smart restaurant and cafe reservation platform designed specifically for the Jordanian market to end the chaos of phone calls and messages, turning reservations into a simple, organized, and reliable experience. Instead of calling and waiting, you can now book your table within seconds — with total clarity.",
        whyTableEase: "Why TableEase?",
        painPoints: [
            "Unanswered calls",
            "Piled up WhatsApp messages",
            "Errors in dates and guest counts"
        ],
        solution: "TableEase solves this from the root through:",
        featuresDiner: {
            title: "What we offer for Diners?",
            list: [
                "Fast booking without account creation",
                "Clear view of available times",
                "Save favorite restaurants",
                "Perfect mobile experience",
                "Full Arabic support"
            ]
        },
        featuresRestaurant: {
            title: "What we offer for Restaurants & Cafes?",
            list: [
                "Control panel to manage bookings easily",
                "Smart table distribution",
                "Reducing no-shows via Deposit system",
                "Peak time insights for operation improvement",
                "Practical tools without technical complexity"
            ]
        },
        ourVision: "Our Vision",
        visionContent: "To become the first reservation platform in Jordan, then expand regionally, maintaining a simple experience for customers and effective tools for restaurants.",
        partnership: "Our Partnership with Venues",
        partnershipContent: "We don't impose complex solutions or heavy commissions. We build long-term partnerships with restaurants and cafes because their success is our success.",
        aboutStatus: "TableEase Today",
        statusContent: "In early launch phase in Jordan, constantly developing based on user and restaurant needs.",
        startNow: "Start Now",
        exploreRest: "Discover Restaurants",
        joinAsRest: "Join as a Restaurant",
        statsAbout: {
            title: "Our Impact in Numbers",
            subtitle: "Redefining the dining experience across Jordan with data-driven hospitality.",
            bookings: "Managed Bookings",
            venues: "Partner Venues",
            users: "Happy Diners",
            cities: "Local Cities"
        },
        // Dashboard
        dashboard: "Dashboard",
        overview: "Overview",
        myRestaurant: "My Venue",
        bookings: "Bookings",
        settings: "Settings",
        logout: "Logout",
        stats: {
            totalBookings: "Total Bookings",
            revenue: "Revenue",
            views: "Page Views",
            rating: "Rating",
            new: "new",
            lastWeekTrend: "+0% from last week",
            noData: "No data yet",
            noRatings: "No ratings"
        },
        manageRestaurant: "Manage Venue",
        restaurantName: "Venue Name",
        cuisineType: "Cuisine / Type",
        saveChanges: "Save Changes",
        recentBookings: "Recent Bookings",
        // statusLabel: "Status", (consist with line 72)
        actions: "Actions",
        accept: "Accept",
        reject: "Reject",
        pending: "Pending",
        confirmed: "Confirmed",
        loginAsPartner: "Restaurant / Café Owner",
        loginAsDiner: "Customer",
        welcomeBack: "Welcome back",
        todayOverview: "here's what's happening today.",
        connect: "Connect",
        userNameLabel: "User",
        guestEmail: "guest@example.com",
        // Register
        createAccount: "Create Account",
        joinMessage: "Join TableEase today",
        confirmPassword: "Confirm Password",
        alreadyHaveAccount: "Already have an account?",
        // Payment
        payment: "Payment",
        paymentDesc: "Secure your reservation with a deposit.",
        payWith: "Pay with",
        creditCard: "Credit / Debit Card",
        cliq: "CliQ (Instant Pay)",
        cardNumber: "Card Number",
        expiryDate: "Expiry Date",
        cvv: "CVV",
        cardHolder: "Cardholder Name",
        cliqAlias: "CliQ Alias / Mobile",
        payNow: "Pay Now",
        reservationDeposit: "Reservation Deposit",
        amount: "Amount",
        loginToBook: "Please login to make a reservation.",
        // Validation
        invalidEmailFormat: "Invalid email format",
        passwordsDoNotMatch: "Passwords do not match!",
        passwordStrength: "Password must be strong (8+ chars, 1 uppercase, 1 number, 1 special char).",
        isRequired: "This field is required",
        invalidPhone: "Invalid phone number format",
        bookingError: "Something went wrong with your booking.",
        loginFailed: "Invalid email or password",
        errorOccurred: "An error occurred, please try again.",
        // Dashboard Generic
        homePage: "Home Page",
        profile: "Profile",
        success: "Success",
        changesSaved: "Changes saved successfully!",
        fillNames: "Please fill in names (AR & EN)",
        resCreated: "Restaurant created successfully",
        resUpdateFailed: "Failed to save restaurant",
        adminDashboard: "Admin Dashboard",
        allRestaurants: "All Restaurants",
        addNewRestaurant: "Add New Restaurant",
        // My Restaurant
        generalInfo: "General Information",
        description: "Description",
        seatingCapacity: "Seating & Capacity",
        mainHall: "Main Hall / Area",
        terrace: "Outdoor / Terrace",
        photos: "Photos",
        location: "Location",
        addressCity: "Address / City",
        priceRange: "Price Range",
        amenities: "Amenities",
        dishName: "Item Name",
        dishDesc: "Item Description",
        price: "Price",
        addDish: "Add Item",
        nameEn: "Venue Name (EN)",
        nameAr: "Venue Name (AR)",
        descEn: "Description (EN)",
        descAr: "Description (AR)",
        // Payments
        checkout: "Checkout",
        payByCard: "Credit/Debit Card",
        payByCliq: "CliQ Transfer",
        payByWallet: "E-Wallet",
        payAtRestaurant: "Pay at Restaurant",
        clicAliasLabel: "Your CliQ Alias / Mobile",
        walletNumLabel: "Wallet Mobile Number",
        confirmPay: "Confirm Payment",
        processing: "Processing...",
        paymentNote: "Secure payment powered by TableEase",
        bookingRequestReceived: "Booking Request Received ⏳",
        bookingPendingMsg: "We have received your request. We will review it and send a WhatsApp confirmation shortly.",
        bookingSentWhatsApp: "Your booking is confirmed! Send the details via WhatsApp to finalize.", // Keep for legacy or unexpected flows
        noPrepayment: "No prepayment needed",

        // Admin WhatsApp Messages
        whatsappConfirmMsg: "Hello, your booking at *{restaurant}* has been confirmed! ✅\nWe look forward to hosting you.",
        whatsappRejectMsg: "Hello, regarding your booking at *{restaurant}*.\nUnfortunately, we cannot confirm your reservation due to full capacity. ❌\nWe apologize for the inconvenience.",
        priceLevels: {
            budget: "Budget ($)",
            casual: "Casual ($$)",
            upscale: "Upscale ($$$)",
            luxury: "Luxury ($$$$)"
        },

        // Common
        comingSoon: "Coming Soon",
        noResults: "No results found for your search.",
        helpCenter: "Help Center",
        termsOfService: "Terms of Service",
        privacyPolicy: "Privacy Policy",
        copyright: "All rights reserved.",
        noRestaurants: "No venues added yet.",
        seeMore: "See More",

        // Settings
        account: "Account",
        personalInfo: "Personal Information",
        edit: "Edit",
        preferences: "Preferences",
        change: "Change",
        theme: "Theme",
        darkMode: "Dark Mode",
        lightMode: "Light Mode",
        notifications: "Notifications",
        emailSMS: "Email & SMS",
        configure: "Configure",
        security: "Password & Security",
        lastChanged: "Last changed recently",
        update: "Update",
        editProfile: "Edit Profile",
        notificationPreferences: "Notification Preferences",
        emailNotifications: "Email Notifications",
        smsAlerts: "SMS Alerts",
        promotionalOffers: "Promotional Offers",
        updatePassword: "Update Password",
        currentPassword: "Current Password",
        newPassword: "New Password",
        cancel: "Cancel",
        bookingFailed: "Booking Failed",
        noSuitableTablesFound: "No suitable tables available for this time and guest count.",
        createRestaurant: "Create Restaurant",
        editRestaurant: "Edit Restaurant",
        updateRestaurant: "Update Restaurant",
        upload: "Upload",
        deleteRestaurantConfirm: "Are you sure you want to delete this restaurant? This action cannot be undone.",
        updateRestaurantDetails: "Update restaurant details",
        createRestaurantListing: "Create a new restaurant listing",
        confirmPassword: "Confirm Password",
        saveChanges: "Save Changes",
        livePreview: "Live Preview",
        chooseSymbolicAvatar: "Meaningful Avatars",
        customPhotoUrl: "Custom Photo URL",
        avatarPlaceholder: "Paste image link here...",
        currentPassPlaceholder: "Enter current password",
        newPassPlaceholder: "Enter new password",
        confirmPassPlaceholder: "Confirm new password",
        roleAdmin: "Platform Admin",
        roleManager: "Manager",
        roleChef: "Master Chef",
        roleStaff: "Floor Staff",
        roleOwner: "Restaurant Owner",
        roleSuperAdmin: "Super Admin",
        roleCustomer: "Customer",
        roleSupervisor: "Supervisor",
        roleConcierge: "Concierge",
        roleModerator: "Moderator",
        success: "Success",
        error: "Error",
        noAmenitiesSelected: "No amenities selected. Add some below!",
        isRequired: "Is required",
        invalidEmailFormat: "Invalid email format",
        invalidPhone: "Invalid phone number",
        saving: "Saving...",
        seconds: "seconds",
        minutes: "min",
        to: "to",
        current: "Current",
        suggested: "Suggested",
        specialOffers: "Special Offers",
        appliedOffer: "Applied Offer",
        discountValue: "Discount Value",
        totalToPay: "Total to Pay",
        originalDeposit: "Original Deposit",
        addNewOffer: "Add New Offer",
        active: "Active",
        inactive: "Inactive",
        // statusField: "Status", (consist with line 72)
        descriptionLabel: "Description",
        tableManagementDesc: "Manage your individual tables, their capacities, and smart allocation settings.",
        pplShort: "ppl",
        auto: "AUTO",
        acceptAndWhatsapp: "Accept & WhatsApp",
        rejectAndWhatsapp: "Reject & WhatsApp",
        tablePlaceholder: "Table 1",
        persons: "Persons",
        disabled: "Disabled",
        cuisines: {
            "Jordanian": "Jordanian",
            "Italian": "Italian",
            "International": "International",
            "Levantine": "Levantine",
            "Cafe": "Cafe"
        },
        priceLevels: {
            "$": "Affordable",
            "$$": "Moderate",
            "$$$": "Premium",
            "$$$$": "Luxury"
        },
        eliteTagline: "Elite Restaurants & Cafes",
        accessDenied: "Access Denied",
        noPermission: "You do not have permission to access the admin dashboard.",
        returnPrevious: "Return to Previous Page",
        manageRestaurants: "Manage Restaurants",
        manageOffers: "Exclusive Promotions",
        restaurantsTab: "Restaurants",
        exclusiveOffersTab: "Platform Offers",
        addOffer: "Create New Offer",
        editOffer: "Update Offer",
        offerTitle: "Offer Title",
        offerDiscount: "Discount/Deal",
        offerExpiry: "Valid Until",
        allRestaurants: "All Restaurants",
        updateRestaurantDetails: "Update your restaurant's profile and information.",
        createRestaurantListing: "List your restaurant on TableEase.",
        fullAddress: "Full Address",
        streetCityFormat: "Format: Street, City",
        pasteOrUpload: "Paste an image URL above or upload a file",
        restaurantImgLabel: "Restaurant Image",
        previewLoaded: "Image preview loaded. In production, this would be uploaded to cloud storage.",
        tellUsEn: "Tell us about your restaurant in English...",
        tellUsAr: "Tell us about your restaurant in Arabic...",
        dishNamePlaceholder: "Dish Name",
        dishDescPlaceholder: "Dish Description",
        pricePlaceholder: "Price",

        // Platform Admin
        platformControl: "Platform Control",
        globalDashboard: "Global Dashboard",
        restaurantsManagement: "Restaurants & Cafés Management",
        offersManagement: "Global Offers Management",
        usersManagement: "User Management",
        analyticsInsights: "Analytics & Insights",
        financials: "Financials",
        contentSEO: "Content & SEO",
        securityLogs: "Security Logs",
        totalRestaurants: "Total Restaurants",
        activeUsers: "Active Users",
        platformVisits: "Platform Visits",
        activePromotions: "Active Promotions",
        recentExplorers: "Recent Explorers",
        platformAlerts: "Platform Alerts",
        manageEntities: "Manage Entities",
        manageEntitiesDesc: "Control every restaurant and cafe on the platform.",
        addNewEntity: "Add New Entity",
        globalOffers: "Global Offers",
        globalOffersDesc: "Create and manage exclusive deals across the entire platform.",
        newCampaign: "New Campaign",
        userAuth: "User Auth",
        userAuthDesc: "Manage platform roles, access control and security logs.",
        systemOnline: "System Online",
        actionRequired: "Action Required",
        manualReview: "Manual Review Recommended",
        seeAll: "See All",
        userDetails: "User Details",
        platformRole: "Platform Role",
        accountStatus: "Account Status",
        actions: "Actions",
        edit: "Edit",
        delete: "Delete",
        suspend: "Suspend",
        activate: "Activate",
        searchUsers: "Search users by name, email or ID...",
        searchEntities: "Search by name, city or ID...",
        searchOffers: "Search campaigns or restaurants...",
        all: "All",
        restaurant: "Restaurant",
        cafe: "Cafe",

        // Analytics
        insightsDesc: "Deep dive into platform interaction and performance.",
        last30Days: "Last 30 Days",
        exportReport: "Export Report",
        clickRate: "Click-Through Rate",
        retention: "User Retention",
        sessionTime: "Avg. Session Time",
        socialShares: "Social Shares",
        traffic: "Platform Traffic",
        sources: "Visit Sources",

        // Financials
        revenueDesc: "Platform revenue monitoring and subscription management.",
        estRevenue: "Estimated Revenue",
        payouts: "Pending Payouts",
        transactions: "Recent Transactions",
        payoutReport: "Financial Report",

        // SEO
        seoDesc: "Manage platform metadata, descriptions and social sharing cards.",
        metaConfig: "Meta Configuration",
        siteTitle: "Site Title",
        siteDesc: "Meta Description",
        keywords: "Keywords",
        preview: "Card Preview",
        saveChanges: "Save Changes",

        // Security
        securityDesc: "Monitoring all sensitive administrative actions and access attempts.",
        auditTrail: "Audit Trail",
        emergency: "Emergency Lockdown",
        blocked: "Threats Blocked",
        onlineNow: "Users Online",
        serviceEntity: "Service/Entity",
        date: "Date",
        amount: "Amount",
        // statusGeneral: "Status", (consist with line 72)
        severity: "Severity",

        // Customer Profile Area
        myFavorites: "My Favorites",
        favorites: "Favorites",
        noFavoritesYet: "No favorites yet",
        startExploring: "Start exploring to save your favorite spots!",
        savedPlaces: "saved places",
        searchFavorites: "Search favorites...",
        recentlyViewed: "Recently Viewed",
        noRecentViews: "No recently viewed venues",
        newAlerts: "New",
        newOfferAlert: "New Exclusive Offer!",
        favoriteUpdate: "Favorite Update",
        offerExpiring: "Offer Expiring Soon!",
        welcomeToTableEase: "Welcome to TableEase!",
        noNotifications: "No notifications",
        allCaughtUp: "You're all caught up!",
        markAllRead: "Mark all read",
        unread: "unread",
        clearAllNotifications: "Clear all notifications",
        venueType: "Venue Type",
        accountSettings: "Account Settings",
        guest: "Guest",
        manageYourAccount: "Manage your account preferences",
        receiveEmailUpdates: "Receive updates via email",
        receiveSmsAlerts: "Get alerted via SMS",
        receiveOffers: "Special deals and discounts",
        lastChanged: "Last changed recently",
        managePrivacy: "Control your data",
        updatePassword: "Update Password",
        privacySettings: "Privacy Settings",
        security: "Security",
        emailNotifications: "Email Notifications",
        smsAlerts: "SMS Alerts",
        promotionalOffers: "Promotional Offers",
        change: "Change",
        cancel: "Cancel",
        edit: "Edit",
        fullName: "Full Name",
        saveChanges: "Save Changes",
        darkMode: "Dark Mode",
        enabled: "Enabled",
        disabled: "Disabled",
        profile: "Profile",
        roleCustomer: "Customer",
        welcomeBack: "Welcome back",
        all: "All",
        viewAll: "View All",
        fileTooLarge: "Image must be less than 2MB",
        avatarUpdated: "Profile picture updated!",
        passwordUpdated: "Password updated successfully!",
        passwordTooShort: "Password must be at least 8 characters",
        publicProfile: "Public Profile",
        allowDiscovery: "Allow others to find your profile",
        activityStatus: "Activity Status",
        showOnlineStatus: "Show when you are active",
        marketingCookies: "Marketing Cookies",
        personalizedAds: "Receive personalized advertisements"
    },
    ar: {
        home: "الرئيسية",
        explore: "استكشف",
        offers: "العروض",
        about: "من نحن",
        login: "تسجيل دخول",
        searchPlaceholder: "ابحث عن مطاعم، كافيهات، مأكولات...",
        searchBtn: "بحث",
        heroTitle: "اكتشف واحجز أرقى الوجهات العالمية",
        heroSubtitle: "أسهل طريقة للعثور على مطعمك أو مقهاك المفضل التالي في الأردن. حجوزات سلسة، عروض حصرية، وتجارب لا تُنسى.",
        featuredTitle: "أماكن مختارة",
        featuredSubtitle: "مطاعم ومقاهي راقية مفضلة، تم اختيارها بعناية من قبل TableEase لتجربة طعام استثنائية.",
        viewAll: "عرض الكل",
        exclusiveOffers: "عروض حصرية",
        limitedTime: "لفترة محدودة",
        exploreDining: "استكشف الأماكن",
        discoverDesc: "اكتشف أرقى وجهات الطعام في الأردن وجرب نكهات لا تُنسى.",
        viewDetails: "التفاصيل",
        bookTable: "احجز طاولة",
        claimNow: "احصل عليه الآن",
        offersSubtitle: "عروض حصرية ولفترة محدودة من شركائنا المختارين.",
        restaurantNotFound: "المكان غير موجود.",
        noMenuHighlights: "لا يوجد أصناف مميزة مضافة بعد.",
        openingHours: "ساعات العمل",
        contact: "تواصل معنا",
        aboutExperience: "عن المكان",
        popularDishes: "خيارات شائعة",
        viewMenu: "عرض القائمة الكاملة",
        fullMenu: "القائمة الكاملة",
        makeReservation: "قم بالحجز",
        completeReservation: "إكمال الحجز",
        selectDate: "اختر التاريخ",
        time: "الوقت",
        guests: "الضيوف",
        continue: "متابعة",
        back: "رجوع",
        confirmBooking: "تأكيد الحجز",
        requests: "الطلبات",
        bookingsManagement: "إدارة الحجوزات",
        idLabel: "المعرف",
        dateTime: "التاريخ والوقت",
        contactLabel: "الاتصال",
        noBookingsFound: "لم يتم العثور على حجوزات.",
        deleteHistoryConfirm: "هل أنت متأكد من رغبتك في مسح سجل الحجوزات بالكامل؟",
        clearHistory: "مسح السجل",
        fullName: "الاسم الكامل",
        email: "البريد الإلكتروني",
        phone: "رقم الهاتف",
        bookingConfirmed: "تم الحجز بنجاح!",
        bookingSent: "لقد أرسلنا رسالة تأكيد إلى",
        done: "تم",
        footerDesc: "نجعل زياراتك لا تُنسى. احجز أفضل الطاولات، واكتشف نكهات جديدة، واستمتع بخدمة سلسة في أرقى مطاعم وكافيهات الأردن.",
        quickLinks: "روابط سريعة",
        support: "دعم",
        newsletter: "النشرة الإخبارية",
        subscribe: "اشترك للحصول على أحدث العروض والتحديثات.",
        tagline: "TableEase • منصة الحجوزات الذكية للمطاعم والكافيهات في الأردن",
        helpCenter: "مركز المساعدة",
        termsOfService: "شروط الخدمة",
        privacyPolicy: "سياسة الخصوصية",
        lastUpdatedLabel: "آخر تحديث",
        january2025: "يناير 2025",
        privacyQuote: "ثقتكم هي أغلى ما نملك. نحن نعامل بياناتكم بنفس العناية التي نعامل بها بياناتنا الخاصة.",
        privacyTeam: "— فريق TableEase",
        stillQuestions: "ما زال لديك أسئلة؟",
        stillQuestionsDesc: "إذا كنت بحاجة إلى توضيح بشأن أي من شروطنا، من فضلك لا تتردد في التواصل مع فريق الدعم لدينا.",
        contactSupport: "تواصل مع الدعم",
        faqTitle: "الأسئلة الشائعة",
        faqs: [
            {
                q: "كيف أقوم بحجز طاولة؟",
                a: "اختر المطعم، حدّد التاريخ والوقت وعدد الأشخاص، ثم أدخل بياناتك واضغط “تأكيد الحجز”."
            },
            {
                q: "هل أحتاج إلى إنشاء حساب؟",
                a: "لا. يمكنك الحجز مباشرة عبر Quick Reserve باستخدام اسمك ورقم هاتفك فقط."
            },
            {
                q: "ماذا يعني أن الحجز “قيد المراجعة”؟",
                a: "يعني أن طلبك تم إرساله للمطعم وهو بانتظار التأكيد أو الرفض من الإدارة."
            },
            {
                q: "هل يمكنني إلغاء الحجز؟",
                a: "يعتمد ذلك على سياسة المطعم. في حال وجود Deposit، قد تنطبق شروط خاصة."
            },
            {
                q: "كيف أضيف مطعم إلى المفضلة؟",
                a: "اضغط على أيقونة ❤️ داخل صفحة المطعم، وسيتم حفظه في قائمة المفضلة لديك."
            },
            {
                q: "أنا صاحب مطعم، كيف أنضم؟",
                a: "يمكنك التسجيل عبر صفحة 'انضم كمطعم' وسنتواصل معك لإعداد حسابك."
            }
        ],
        welcomeBackAdmin: "أهلاً بك مرة أخرى، المسؤول",
        noResults: "لا توجد نتائج.",
        exclusiveOffer: "عرض حصري",
        vibeFinderTitle: "بوصلة الذوق المثالي",
        vibeFinderSubtitle: "أجب عن 4 أسئلة سريعة وسنجد لك المكان المثالي لذوقك.",
        startVibeFinder: "ابدأ البحث الذكي",
        termsContent: [
            {
                title: "1. مقدمة",
                desc: "باستخدامك لمنصة TableEase، فإنك توافق على الالتزام بشروط الخدمة الموضحة أدناه."
            },
            {
                title: "2. طبيعة الخدمة",
                desc: "TableEase هي منصة وسيطة تربط بين المستخدمين والمطاعم، ولا تتحمل مسؤولية جودة الخدمة المقدمة داخل المطعم."
            },
            {
                title: "3. الحجوزات",
                desc: "الحجز يخضع لموافقة المطعم. قد يتم رفض أو تعديل الحجز حسب توفر الطاولات. بعض الحجوزات قد تتطلب دفع مبلغ تأميني (Deposit)."
            },
            {
                title: "4. الإلغاء وعدم الحضور",
                desc: "سياسات الإلغاء تختلف من مطعم لآخر. في حال عدم الحضور، قد يتم خصم مبلغ التأمين حسب سياسة المطعم."
            },
            {
                title: "5. الاستخدام المقبول",
                desc: "يُمنع: إساءة استخدام المنصة، تقديم معلومات غير صحيحة، محاولة تعطيل النظام أو إساءة استغلاله."
            },
            {
                title: "6. التعديلات",
                desc: "تحتفظ TableEase بحق تعديل هذه الشروط في أي وقت، وسيتم إشعار المستخدمين عند حدوث تغييرات جوهرية."
            }
        ],
        privacyContent: [
            {
                title: "1. جمع المعلومات",
                desc: "نقوم بجمع المعلومات التالية: الاسم، رقم الهاتف، تفاصيل الحجز، تفضيلات المستخدم (مثل المطاعم المفضلة)."
            },
            {
                title: "2. استخدام المعلومات",
                desc: "نستخدم بياناتك من أجل: إتمام الحجوزات، تحسين تجربة المستخدم، التواصل بخصوص الحجز."
            },
            {
                title: "3. مشاركة البيانات",
                desc: "لا نقوم ببيع أو مشاركة بياناتك مع أطراف خارجية، باستثناء: المطعم الذي تم الحجز لديه، خدمات الدفع عند الحاجة."
            },
            {
                title: "4. حماية البيانات",
                content: "نلتزم باتخاذ إجراءات تقنية وتنظيمية لحماية بيانات المستخدمين من الوصول غير المصرح به."
            },
            {
                title: "5. ملفات تعريف الارتباط (Cookies)",
                desc: "قد نستخدم ملفات تعريف الارتباط لتحسين الأداء وتجربة الاستخدام."
            },
            {
                title: "6. حقوق المستخدم",
                desc: "يحق لك: طلب تعديل بياناتك، طلب حذف بياناتك، الاستفسار عن كيفية استخدام معلوماتك."
            }
        ],
        guarantee: "ضمان",
        available: "متاح",
        arabic: "عربي",
        english: "إنجليزي",
        join: "انضم",
        rights: "TableEase. جميع الحقوق محفوظة.",
        cuisines: {
            All: "الكل",
            Jordanian: "أردني",
            Italian: "إيطالي",
            Cafe: "كافيه",
            Levantine: "شامي",
            International: "عالمي"
        },
        loginTitle: "أهلاً بك مجدداً",
        loginSubtitle: "سجل دخولك لإدارة مطعمك أو كافيهك على TableEase",
        password: "كلمة المرور",
        signIn: "دخول",
        noAccount: "تملك مطعم أو كافيه؟",
        register: "انضم إلى TableEase",
        aboutTitle: "TableEase",
        aboutTagline: "احجز طاولتك بثوانٍ. واترك الفوضى خلفك.",
        aboutDescription: "TableEase هي منصة حجز مطاعم وكافيهات ذكية صُممت خصيصًا للسوق الأردني، لتُنهِي فوضى الاتصالات والرسائل، وتحوّل الحجز إلى تجربة بسيطة، منظمة، وموثوقة. بدل الاتصال والانتظار، يمكنك الآن حجز طاولتك خلال ثوانٍ — وبكل وضوح.",
        whyTableEase: "لماذا TableEase؟",
        painPoints: [
            "مكالمات لا تُجاب",
            "رسائل واتساب متراكمة",
            "أخطاء في المواعيد وعدد الضيوف"
        ],
        solution: "TableEase يحل هذه المشكلة من جذورها عبر:",
        featuresDiner: {
            title: "ماذا نقدم للزبائن؟",
            list: [
                "حجز سريع بدون إنشاء حساب",
                "عرض الأوقات المتاحة بوضوح",
                "حفظ المطاعم المفضلة",
                "تجربة استخدام مثالية على الهاتف",
                "دعم كامل للغة العربية"
            ]
        },
        featuresRestaurant: {
            title: "ماذا نقدم للمطاعم والكافيهات؟",
            list: [
                "لوحة تحكم لإدارة الحجوزات بسهولة",
                "توزيع ذكي للطاولات",
                "تقليل حالات عدم الحضور عبر نظام Deposit",
                "معرفة أوقات الذروة لتحسين التشغيل",
                "أدوات عملية بدون تعقيد تقني"
            ]
        },
        ourVision: "رؤيتنا",
        visionContent: "أن تصبح TableEase المنصة الأولى لحجوزات المطاعم في الأردن، ثم التوسع إقليميًا، مع الحفاظ على تجربة بسيطة للزبائن وأدوات فعالة للمطاعم.",
        partnership: "شراكتنا مع المطاعم والكافيهات",
        partnershipContent: "نحن لا نفرض حلولًا معقدة ولا عمولات مرهقة. نحن نبني شراكة طويلة الأمد مع المطاعم والكافيهات، لأن نجاح شركائنا هو أساس نجاحنا.",
        aboutStatus: "TableEase اليوم",
        statusContent: "TableEase في مرحلة الإطلاق الأولي داخل الأردن، ونعمل باستمرار على تطوير المنصة وتحسين التجربة بناءً على احتياجات المستخدمين والمطاعم.",
        startNow: "ابدأ الآن",
        exploreRest: "اكتشف المطاعم",
        joinAsRest: "انضم كمطعم",
        statsAbout: {
            title: "تأثيرنا لغة الأرقام",
            subtitle: "نحن نعيد تعريف تجربة الطعام في الأردن عبر حلول ضيافة مدعومة بالبيانات.",
            bookings: "حجز مُدار",
            venues: "شريك منشأة",
            users: "مستخدم سعيد",
            cities: "مدن محلية"
        },
        // Dashboard
        dashboard: "لوحة التحكم",
        overview: "نظرة عامة",
        myRestaurant: "مكاني / منشأتي",
        bookings: "الحجوزات",
        settings: "الإعدادات",
        logout: "تسجيل خروج",
        stats: {
            totalBookings: "مجموع الحجوزات",
            revenue: "الإيرادات",
            views: "المشاهدات",
            rating: "التقييم",
            new: "جديد",
            lastWeekTrend: "+0% من الأسبوع الماضي",
            noData: "لا يوجد بيانات بعد",
            noRatings: "لا يوجد تقييمات"
        },
        manageRestaurant: "إدارة المكان",
        restaurantName: "اسم المكان",
        cuisineType: "نوع المطبخ / الفئة",
        saveChanges: "حفظ التغييرات",
        recentBookings: "آخر الحجوزات",
        status: "الحالة",
        actions: "إجراءات",
        accept: "قبول",
        reject: "رفض",
        pending: "قيد الانتظار",
        confirmed: "مؤكد",
        welcomeBack: "أهلاً بك مجدداً",
        todayOverview: "إليك آخر التحديثات لهذا اليوم.",
        connect: "اتصال",
        userNameLabel: "مستخدم",
        guestEmail: "guest@example.com",
        loginAsPartner: "صاحب مطعم / كافيه",
        loginAsDiner: "زبون",
        // Register
        createAccount: "إنشاء حساب",
        joinMessage: "انضم إلى TableEase اليوم",
        confirmPassword: "تأكيد كلمة المرور",
        alreadyHaveAccount: "لديك حساب بالفعل؟",
        // Payment
        payment: "الدفع",
        paymentDesc: "قم بتأكيد حجزك بدفع العربون.",
        payWith: "ادفع بواسطة",
        creditCard: "بطاقة ائتمان / خصم",
        cliq: "كليك (دفع فوري)",
        cardNumber: "رقم البطاقة",
        expiryDate: "تاريخ الانتهاء",
        cvv: "CVV",
        cardHolder: "اسم حامل البطاقة",
        cliqAlias: "اسم كليك المستعار / الموبايل",
        payNow: "ادفع الآن",
        reservationDeposit: "عربون الحجز",
        amount: "المبلغ",
        loginToBook: "يرجى تسجيل الدخول للحجز.",
        // Validation
        invalidEmailFormat: "صيغة البريد الإلكتروني غير صحيحة",
        passwordsDoNotMatch: "كلمتا المرور غير متطابقتين!",
        passwordStrength: "يجب أن تكون كلمة المرور قوية (8+ أحرف، كبير، صغير، رقم، رمز).",
        isRequired: "هذا الحقل مطلوب",
        invalidPhone: "رقم الهاتف غير صحيح",
        bookingError: "حدث خطأ ما أثناء معالجة حجزك.",
        loginFailed: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
        errorOccurred: "حدث خطأ ما، يرجى المحاولة مرة أخرى.",

        // Common
        comingSoon: "قريباً",
        noResults: "لم يتم العثور على نتائج لبحثك.",
        helpCenter: "مركز المساعدة",
        allBookings: "جميع الحجوزات",
        today: "اليوم",
        tomorrow: "غداً",
        thisWeek: "هذا الأسبوع",
        tableManagement: "إدارة الطاولات",
        addTable: "إضافة طاولة",
        tableName: "اسم/رقم الطاولة",
        capacity: "السعة",
        // status: "الحالة", (duplicate)
        active: "نشط",
        disabled: "غير نشط",
        noTables: "لا توجد طاولات معرفة. أضف طاولتك الأولى!",
        suitableTableAllocated: "تم تخصيص طاولة مناسبة لك تلقائياً.",
        noSuitableTables: "لا توجد طاولات مناسبة متاحة في هذا الوقت.",
        tableSettings: "إعدادات الطاولات",
        saveTable: "حفظ الطاولة",
        editTable: "تعديل الطاولة",
        deleteTable: "حذف الطاولة",
        persons: "أشخاص",
        defaultDuration: "المدة الافتراضية (بالدقائق)",
        bufferTime: "وقت التجهيز (بالدقائق)",
        termsOfService: "شروط الخدمة",
        privacyPolicy: "سياسة الخصوصية",
        copyright: "جميع الحقوق محفوظة.",
        noRestaurants: "لم يتم إضافة أي أماكن بعد.",
        seeMore: "عرض المزيد",

        // Dashboard Generic
        homePage: "الرئيسية للموقع",
        profile: "الملف الشخصي",
        success: "نجاح",
        changesSaved: "تم حفظ التغييرات بنجاح!",
        fillNames: "يرجى تعبئة أسماء المكان (بالعربي والإنجليزي)",
        resCreated: "تم إنشاء المكان بنجاح",
        resUpdateFailed: "فشل في حفظ بيانات المكان",
        adminDashboard: "لوحة تحكم المسؤول",
        allRestaurants: "جميع الأماكن",
        addNewRestaurant: "إضافة مكان جديد",
        // My Restaurant
        generalInfo: "معلومات عامة",
        description: "الوصف",
        seatingCapacity: "المقاعد والسعة",
        mainHall: "الصالة الرئيسية / الساحة",
        terrace: "الجلسات الخارجية / التراس",
        photos: "الصور",
        location: "الموقع",
        addressCity: "العنوان / المدينة",
        priceRange: "نطاق الأسعار",
        amenities: "المرافق",
        dishName: "اسم الصنف",
        dishDesc: "وصف الصنف",
        price: "السعر",
        addDish: "إضافة صنف",
        nameEn: "اسم المكان (EN)",
        nameAr: "اسم المكان (AR)",
        descEn: "الوصف (EN)",
        descAr: "الوصف (AR)",
        // Payments
        checkout: "الدفع",
        payByCard: "بطاقة ائتمان",
        payByCliq: "تحويل كليك",
        payByWallet: "محفظة إلكترونية",
        payAtRestaurant: "الدفع عند الوصول",
        clicAliasLabel: "اسمك المستعار على كليك / رقم الهاتف",
        walletNumLabel: "رقم المحفظة",
        confirmPay: "تأكيد الدفع",
        processing: "جاري المعالجة...",
        paymentNote: "دفع آمن عبر TableEase",
        bookingRequestReceived: "تم استلام طلب الحجز ⏳",
        bookingPendingMsg: "سيتم مراجعة طلبك وإرسال رسالة تأكيد عبر واتساب خلال وقت قصير.",
        bookingSentWhatsApp: "تم تأكيد الحجز! أرسل التفاصيل عبر الواتساب لإتمامه.",
        noPrepayment: "لا يتطلب دفع مسبق",

        // Admin WhatsApp Messages
        whatsappConfirmMsg: "مرحباً، تم تأكيد حجزك في *{restaurant}* بنجاح! ✅\nشكراً لثقتك بنا، ونتمنى لك تجربة ممتعة.",
        whatsappRejectMsg: "مرحباً، بخصوص حجزك في *{restaurant}*.\nنعتذر، لم يتم تأكيد الحجز بسبب عدم توفر المقاعد. ❌\nيسعدنا خدمتك في وقت آخر.",
        priceLevels: {
            budget: "اقتصادي ($)",
            casual: "متوسط ($$)",
            upscale: "راقي ($$$)",
            luxury: "فاخر ($$$$)"
        },

        // Settings
        account: "الحساب",
        personalInfo: "المعلومات الشخصية",
        edit: "تعديل",
        preferences: "التفضيلات",
        change: "تغيير",
        theme: "المظهر",
        darkMode: "الوضع الليلي",
        lightMode: "الوضع النهاري",
        notifications: "الإشعارات",
        emailSMS: "البريد والرسائل",
        configure: "تكوين",
        security: "الأمان وكلمة المرور",
        lastChanged: "آخر تغيير مؤخراً",
        update: "تحديث",
        editProfile: "تعديل الملف الشخصي",
        notificationPreferences: "تفضيلات الإشعارات",
        emailNotifications: "إشعارات البريد",
        smsAlerts: "تنبيهات SMS",
        promotionalOffers: "عروض ترويجية",
        updatePassword: "تحديث كلمة المرور",
        currentPassword: "كلمة المرور الحالية",
        newPassword: "كلمة المرور الجديدة",
        cancel: "إلغاء",
        bookingFailed: "فشل الحجز",
        noSuitableTablesFound: "لا توجد طاولات مناسبة متاحة لهذا الوقت وعدد الضيوف.",
        createRestaurant: "إنشاء مكان",
        editRestaurant: "تعديل المكان",
        updateRestaurant: "تحديث المكان",
        upload: "رفع صورة",
        deleteRestaurantConfirm: "هل أنت متأكد من حذف هذا المكان؟ لا يمكن التراجع عن هذا الإجراء.",
        updateRestaurantDetails: "تحديث تفاصيل المكان",
        createRestaurantListing: "إنشاء إدراج مكان جديد",
        confirmPassword: "تأكيد كلمة المرور",
        saveChanges: "حفظ التغييرات",
        livePreview: "معاينة مباشرة",
        chooseSymbolicAvatar: "صور رمزية معبرة",
        customPhotoUrl: "رابط صورة مخصص",
        avatarPlaceholder: "الصق رابط الصورة هنا...",
        currentPassPlaceholder: "أدخل كلمة المرور الحالية",
        newPassPlaceholder: "أدخل كلمة المرور الجديدة",
        confirmPassPlaceholder: "تأكيد كلمة المرور الجديدة",
        roleAdmin: "مدير المنصة",
        roleManager: "مدير",
        roleChef: "كبير الطهاة",
        roleStaff: "طاقم العمل",
        roleOwner: "صاحب مطعم/كافيه",
        roleSuperAdmin: "المسؤول الأعلى",
        roleCustomer: "زبون",
        roleSupervisor: "مشرف",
        roleConcierge: "مسؤول الحجز",
        roleModerator: "منظم",
        success: "نجاح",
        error: "خطأ",
        noAmenitiesSelected: "لا توجد مرافق مختارة. أضف بعضها أدناه!",
        isRequired: "مطلوب",
        invalidEmailFormat: "تنسيق البريد غير صحيح",
        invalidPhone: "رقم الهاتف غير صحيح",
        saving: "جاري الحفظ...",
        seconds: "ثانية",
        minutes: "دقيقة",
        to: "إلى",
        current: "الحالي",
        suggested: "مقترح",
        specialOffers: "عروض خاصة",
        appliedOffer: "العرض المطبق",
        discountValue: "قيمة الخصم",
        totalToPay: "المبلغ الإجمالي",
        originalDeposit: "مبلغ التأمين الأصلي",
        addNewOffer: "إضافة عرض جديد",
        active: "نشط",
        inactive: "غير نشط",
        // status: "الحالة", (duplicate)
        descriptionLabel: "الوصف",
        tableManagementDesc: "إدارة الطاولات الفردية، سعاتها، وإعدادات التخصيص الذكي.",
        pplShort: "شخص",
        auto: "تلقائي",
        acceptAndWhatsapp: "قبول وتواصل واتساب",
        rejectAndWhatsapp: "رفض وتواصل واتساب",
        tablePlaceholder: "طاولة 1",
        persons: "أشخاص",
        disabled: "معطل",
        cuisines: {
            "Jordanian": "أردني",
            "Italian": "إيطالي",
            "International": "عالمي",
            "Levantine": "شامي",
            "Cafe": "مقهى"
        },
        priceLevels: {
            "$": "اقتصادي",
            "$$": "متوسط",
            "$$$": "مميز",
            "$$$$": "فاخر"
        },
        eliteTagline: "المطاعم والمقاهي الراقية",
        accessDenied: "تم رفض الوصول",
        noPermission: "ليس لديك الصلاحية للوصول إلى لوحة التحكم.",
        returnPrevious: "العودة للصفحة السابقة",
        manageRestaurants: "إدارة المطاعم",
        manageOffers: "إدارة العروض الحصرية",
        restaurantsTab: "المطاعم",
        exclusiveOffersTab: "عروض المنصة",
        addOffer: "إضافة عرض جديد",
        editOffer: "تحديث العرض",
        offerTitle: "عنوان العرض",
        offerDiscount: "قيمة الخصم/العرض",
        offerExpiry: "صالح لغاية",
        allRestaurants: "جميع المطاعم",
        fullAddress: "العنوان الكامل",
        streetCityFormat: "الصيغة: الشارع، المدينة",
        pasteOrUpload: "الصق رابط الصورة أو ارفع ملفاً",
        restaurantImgLabel: "صورة المطعم",
        previewLoaded: "تم تحميل معاينة الصورة. في النسخة النهائية، سيتم رفعها للتخزين السحابي.",
        tellUsEn: "أخبرنا عن مطعمك بالإنجليزية...",
        tellUsAr: "أخبرنا عن مطعمك بالعربية...",
        dishNamePlaceholder: "اسم الطبق",
        dishDescPlaceholder: "وصف الطبق",
        pricePlaceholder: "السعر",

        // Platform Admin
        platformControl: "إدارة المنصة",
        globalDashboard: "لوحة التحكم العالمية",
        restaurantsManagement: "إدارة المطاعم والكافيهات",
        offersManagement: "إدارة العروض العالمية",
        usersManagement: "إدارة المستخدمين",
        analyticsInsights: "التحليلات والرؤى",
        financials: "القسم المالي",
        contentSEO: "المحتوى والـ SEO",
        securityLogs: "سجلات الأمان",
        totalRestaurants: "إجمالي المطاعم",
        activeUsers: "المستخدمين النشطين",
        platformVisits: "زيارات المنصة",
        activePromotions: "العروض النشطة",
        recentExplorers: "أحدث المنضمين",
        platformAlerts: "تنبيهات المنصة",
        manageEntities: "إدارة المنشآت",
        manageEntitiesDesc: "تحكم في كل مطعم وكافيه على المنصة.",
        addNewEntity: "إضافة منشأة جديدة",
        globalOffers: "العروض العالمية",
        globalOffersDesc: "إنشاء وإدارة العروض الحصرية على مستوى المنصة.",
        newCampaign: "حملة جديدة",
        userAuth: "صلاحيات المستخدمين",
        userAuthDesc: "إدارة أدوار المنصة، التحكم في الوصول وسجلات الأمان.",
        systemOnline: "النظام متصل",
        actionRequired: "إجراء مطلوب",
        manualReview: "ينصح بالمراجعة اليدوية",
        seeAll: "عرض الكل",
        userDetails: "بيانات المستخدم",
        platformRole: "الدور في المنصة",
        accountStatus: "حالة الحساب",
        actions: "إجراءات",
        edit: "تعديل",
        delete: "حذف",
        suspend: "إيقاف",
        activate: "تفعيل",
        searchUsers: "ابحث عن مستخدم بالاسم، البريد أو المعرف...",
        searchEntities: "ابحث بالاسم، المدينة أو المعرف...",
        searchOffers: "ابحث عن الحملات أو المطاعم...",
        all: "الكل",
        restaurant: "مطعم",
        cafe: "كافيه",

        // Analytics
        insightsDesc: "تحليل معمق لتفاعلات المنصة وأدائها العام.",
        last30Days: "آخر 30 يوم",
        exportReport: "تصدير التقرير",
        clickRate: "نسبة النقر",
        retention: "بقاء المستخدمين",
        sessionTime: "متوسط وقت الجلسة",
        socialShares: "المشاركات الاجتماعية",
        traffic: "حركة زوار المنصة",
        sources: "مصادر الزيارات",

        // Financials
        revenueDesc: "مراقبة إيرادات المنصة وإدارة الاشتراكات.",
        estRevenue: "الإيرادات التقديرية",
        payouts: "دفعات معلقة",
        transactions: "أحدث المعاملات",
        payoutReport: "التقرير المالي",

        // SEO
        seoDesc: "إدارة البيانات الوصفية للمنصة، الأوصاف وبطاقات المشاركة الاجتماعية.",
        metaConfig: "إعدادات الميتا",
        siteTitle: "عنوان الموقع",
        siteDesc: "وصف الموقع",
        keywords: "الكلمات الدلالية",
        preview: "معاينة البطاقة",
        saveChanges: "حفظ التغييرات",

        // Security
        securityDesc: "مراقبة جميع الإجراءات الإدارية الحساسة ومحاولات الوصول.",
        auditTrail: "سجل التدقيق",
        emergency: "إغلاق الطوارئ",
        blocked: "تهديدات تم صدها",
        onlineNow: "مستخدمين متاحين",
        serviceEntity: "الخدمة / المنشأة",
        date: "التاريخ",
        amount: "المبلغ",
        // status: "الحالة", (duplicate)
        severity: "الخطورة",

        // Customer Profile Area
        myFavorites: "مفضلاتي",
        favorites: "المفضلة",
        noFavoritesYet: "لا توجد مفضلات بعد",
        startExploring: "ابدأ الاستكشاف لحفظ أماكنك المفضلة!",
        savedPlaces: "أماكن محفوظة",
        searchFavorites: "ابحث في المفضلة...",
        recentlyViewed: "شوهدت مؤخراً",
        noRecentViews: "لم تشاهد أي أماكن مؤخراً",
        newAlerts: "جديد",
        newOfferAlert: "عرض حصري جديد!",
        favoriteUpdate: "تحديث مفضلة",
        offerExpiring: "عرض ينتهي قريباً!",
        welcomeToTableEase: "مرحباً بك في TableEase!",
        noNotifications: "لا توجد إشعارات",
        allCaughtUp: "أنت على اطلاع بكل شيء!",
        markAllRead: "تعيين الكل كمقروء",
        unread: "غير مقروء",
        clearAllNotifications: "مسح كل الإشعارات",
        venueType: "نوع المكان",
        accountSettings: "إعدادات الحساب",
        guest: "زائر",
        manageYourAccount: "إدارة تفضيلات حسابك",
        receiveEmailUpdates: "تلقي التحديثات عبر البريد الإلكتروني",
        receiveSmsAlerts: "احصل على تنبيهات عبر SMS",
        receiveOffers: "عروض وخصومات خاصة",
        lastChanged: "تم التغيير مؤخراً",
        managePrivacy: "التحكم في بياناتك",
        updatePassword: "تحديث كلمة المرور",
        privacySettings: "إعدادات الخصوصية",
        security: "الأمان",
        emailNotifications: "إشعارات البريد",
        smsAlerts: "تنبيهات SMS",
        promotionalOffers: "عروض ترويجية",
        change: "تغيير",
        cancel: "إلغاء",
        edit: "تعديل",
        fullName: "الاسم الكامل",
        saveChanges: "حفظ التغييرات",
        darkMode: "الوضع الليلي",
        enabled: "مفعل",
        disabled: "معطل",
        profile: "الملف الشخصي",
        roleCustomer: "زبون",
        welcomeBack: "أهلاً بك مجدداً",
        all: "الكل",
        viewAll: "عرض الكل",
        fileTooLarge: "يجب أن يكون حجم الصورة أقل من 2 ميجابايت",
        avatarUpdated: "تم تحديث الصورة الشخصية بنجاح!",
        passwordUpdated: "تم تحديث كلمة المرور بنجاح!",
        passwordTooShort: "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",
        publicProfile: "الملف الشخصي العام",
        allowDiscovery: "السماح للآخرين بالعثور على ملفك الشخصي",
        activityStatus: "حالة النشاط",
        showOnlineStatus: "إظهار عندما تكون نشطاً",
        marketingCookies: "ملفات تعريف الارتباط التسويقية",
        personalizedAds: "تلقي الإعلانات المخصصة"
    }
};

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState(() => {
        return localStorage.getItem('tableease_lang') || 'en';
    });

    const toggleLanguage = () => {
        setLanguage(prev => {
            const newLang = prev === 'en' ? 'ar' : 'en';
            localStorage.setItem('tableease_lang', newLang);
            return newLang;
        });
    };

    useEffect(() => {
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
        localStorage.setItem('tableease_lang', language);
    }, [language]);

    return (
        <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t: translations[language] }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => useContext(LanguageContext);
